/* Automatically generated by generate-command-table.py, do not edit. */

/* CONFIG command table */
struct redisCommand CONFIG_Subcommands[] = {
    {"SET",configSetCommand,4,"admin no-script"},
}

/* Main command table */
struct redisCommand redisCommandTable[] = {
    /* generic */
    {"CONFIG",NULL,-2,"",.subcommands=CONFIG_Subcommands},
    {"MIGRATE",migrateCommand,-6,"write random @keyspace @dangerous @write @slow",{{"write",KSPEC_BS_INDEX,.bs.index={3},KSPEC_FK_RANGE,.fk.range={0,1,0}},{"write incomplete",KSPEC_BS_INDEX,.bs.keyword={"KEYS",-2},KSPEC_FK_RANGE,.fk.range={-1,1,0}}},migrateGetKeys},
    /* sorted_set */
    {"ZUNIONSTORE",zunionstoreCommand,-4,"write use-memory @sortedset @write @slow",{{"write",KSPEC_BS_INDEX,.bs.index={1},KSPEC_FK_RANGE,.fk.range={0,1,0}},{"read",KSPEC_BS_INDEX,.bs.index={1},KSPEC_FK_RANGE,.fk.keynum={0,1,1}}},zunionInterDiffStoreGetKeys},
    /* stream */
    {"XADD",xaddCommand,-5,"write use-memory fast random @stream @write @slow",{{"write",KSPEC_BS_INDEX,.bs.index={1},KSPEC_FK_RANGE,.fk.range={0,1,0}}}},
    /* string */
    {"SET",setCommand,-3,"write use-memory @string @write @slow",{{"write",KSPEC_BS_INDEX,.bs.index={1},KSPEC_FK_RANGE,.fk.range={0,1,0}}}},
}

